// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"net/http"
	_ "net/http/pprof"
)

func main() {
	go http.ListenAndServe("localhost:8080", nil)

	h := server.Default()

	register(h)
	h.Spin()
}
