// Code generated by hertz generator.

package apigatewayservice

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agwMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servicenameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apipostMw() []app.HandlerFunc {
	// your code...
	return nil
}
