// Code generated by hertz generator.

package Test

import (
	test "APIGateway/biz/model/Test"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func HandleAll(ctx context.Context, c *app.RequestContext) {
	var req test.Req
	err := c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}
	c.JSON(consts.StatusOK, utils.H{
		"sn": req.ServiceName,
		"mn": req.MethodName,
		"iv": req.IDLVersion,
	})
}
