// Code generated by hertz generator.

package apigatewayservice

import (
	apigatewayservice "APIGateway/biz/model/apigatewayservice"
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
	"github.com/cloudwego/hertz/pkg/common/json"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/genericclient"
	"github.com/cloudwego/kitex/pkg/generic"
	"github.com/cloudwego/kitex/pkg/loadbalance"
	etcd "github.com/kitex-contrib/registry-etcd"
)

// APIPost .
// @router agw/:serviceName/*methodName [POST]
func APIPost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req apigatewayservice.Req
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	r, err := etcd.NewEtcdResolver([]string{"127.0.0.1:2379"})
	if err != nil {
		panic(err)
		return
	}
	var opts []client.Option
	opts = append(opts, client.WithResolver(r))
	opts = append(opts, client.WithLoadBalancer(loadbalance.NewWeightedRandomBalancer()))

	var resp string
	//opts = append(opts, client.WithHostPorts("localhost:9999"))
	p, _ := generic.NewThriftFileProvider("./idls/student.thrift")
	g, _ := generic.JSONThriftGeneric(p)

	cli, _ := genericclient.NewClient(req.ServiceName, g, opts...)
	httpReq, _ := adaptor.GetCompatRequest(c.GetRequest())
	re, err := generic.FromHTTPRequest(httpReq)
	if err != nil {
		fmt.Println(err)
	}
	m := re.Body
	s, _ := json.Marshal(m)
	str := string(s)
	res, err := cli.GenericCall(ctx, req.MethodName, str)

	if err != nil {
		fmt.Println(err)
		return
	}
	resp = res.(string)

	c.JSON(consts.StatusOK, resp)
}
