// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	apigatewayservice "APIGateway/biz/router/apigatewayservice"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	apigatewayservice.Register(r)
}
